# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:

  # Github actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Dubai"
    assignees:
      - "AlexanderDokuchaev"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  # Python
  - package-ecosystem: pip
    directories:
      - "/"
      - "/tests/*"
    exclude-paths:
      - ".ci"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 10
    assignees:
      - "AlexanderDokuchaev"
    versioning-strategy: increase-if-necessary
    groups:
      pytorch:
        patterns:
          - "torch"
          - "torchvision"
          - "torchao"
      pytest:
        patterns:
          - "pytest*"
      onnx:
        patterns:
          - "onnx*"
      python-dependencies:
        patterns:
          - "*"
        group-by: dependency-name
