[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
force_single_line = true
profile = 'black'
single_line_exclusions = ['typing']
