# See help here: https://github.com/marketplace/actions/labeler

dependencies:
  - 'requirements.txt'
  - '**/setup.py'

NNCF PT:
- any:
    - 'examples/torch/**/*'
    - 'examples/post_training_quantization/torch/**/*'
    - 'nncf/torch/**/*'
    - 'tests/torch/**/*'
  all:
    - '!**/*.md'


NNCF PT:
- any:
    - 'examples/torch/**/*'
  all:
    - '!**/*.md'

NNCF TF:
- any:
    - 'examples/tensorflow/**/*'
    - 'examples/post_training_quantization/tensorflow/**/*'
    - 'nncf/tensorflow/**/*'
    - 'tests/tensorflow/**/*'
  all:
    - '!**/*.md'

NNCF ONNX:
- any:
    - 'examples/onnx/**/*'
    - 'examples/post_training_quantization/onnx/**/*'
    - 'nncf/onnx/**/*'
    - 'tests/onnx/**/*'
  all:
    - '!**/*.md'


NNCF OpenVINO:
- any:
    - 'examples/openvino/**/*'
    - 'examples/post_training_quantization/openvino/**/*'
    - 'nncf/openvino/**/*'
    - 'tests/openvino/**/*'
  all:
    - '!**/*.md'

NNCF PTQ:
- any:
    - 'nncf/quantization/**/*'
    - 'tests/post_training/**/*'
  all:
    - '!**/*.md'

documentation:
  - '**/*.md'
  - 'docs/**/*'

experimental:
- any:
    - 'nncf/experimental/**/*'
  all:
    - '!**/*.md'

NNCF Common:
- any:
    - 'examples/common/**/*'
    - 'nncf/common/**/*'
    - 'tests/common/**/*'
  all:
    - '!**/*.md'
