name: API changes check
permissions: read-all

on:
  pull_request:

env:
  API_DOC_HTML_ROOT_RELATIVE_PATH: autoapi

concurrency:
  group: ci-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  compare-api-doc-with-develop:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Add label
        run: |
          echo '{"pr_number": "${{ github.event.pull_request.number }}", "action": "add"}' > api_status.json

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: api_status
          path: api_status.json
