name: Compare requirements
run-name: "Compare requirements with ${{ inputs.compare_with }}"

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      compare_with:
        description: 'The reference to compare with (branch, tag, or commit SHA)'
        type: string
        required: false

env:
  CURRENT_PATH: current
  REFERENCE_PATH: release

jobs:
  compare-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current ref
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ${{ env.CURRENT_PATH }}
          fetch-depth: 0

      - name: Checkout reference ref
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.compare_with }}
          path: ${{ env.REFERENCE_PATH }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Collect current dependencies
        working-directory: ${{ env.CURRENT_PATH }}
        run:
          python3 .github/scripts/collect_all_requirements.py --output "${GITHUB_WORKSPACE}/current_requirements.txt"

      - name: Collect reference dependencies
        working-directory: ${{ env.REFERENCE_PATH }}
        run: |
          set -euo pipefail
          python3 "${GITHUB_WORKSPACE}/${{ env.CURRENT_PATH }}/.github/scripts/collect_all_requirements.py" \
            --output "${GITHUB_WORKSPACE}/release_requirements.txt"

      - name: Upload comparison artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: requirements-compare
          path: |
            "release_requirements.txt"
            "current_requirements.txt"
          if-no-files-found: ignore

      - name: Summary
        if: always()
        run: |
          {
            echo "## Added dependencies:"
            echo
            printf '%s\n' '```diff'
            comm -23 "release_requirements.txt" "current_requirements.txt" || true
            printf '%s\n' '```'
            echo "## Removed dependencies:"
            echo
            printf '%s\n' '```diff'
            comm -13 "release_requirements.txt" "current_requirements.txt" || true
            printf '%s\n' '```'
          } >> "${GITHUB_STEP_SUMMARY}"
