name: Test examples
permissions: read-all

on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  pull_request:

jobs:
  examples:
    runs-on: aks-linux-16-cores-32gb
    container:
      image: openvinogithubactions.azurecr.io/dockerhub/ubuntu:20.04
      volumes:
        - /mount:/mount
    env:
      DEBIAN_FRONTEND: noninteractive # to prevent apt-get from waiting user input
    defaults:
      run:
        shell: bash

    steps:
      - name: Install dependencies
        run : |
          apt-get update
          apt-get install --assume-yes --no-install-recommends git git-lfs lsb-release ca-certificates build-essential ninja-build libgl1-mesa-dev libglib2.0-0
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
            lfs: true
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.10.14
          # cache: pip
      - name: cpuinfo
        run: cat /proc/cpuinfo
      - name: Install NNCF and test requirements
        run: |
          pip install -e .
          pip install -r tests/cross_fw/examples/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run examples test scope
        run: python -m pytest -ra tests/cross_fw/examples -s -k "not llm"
        env:
          TQDM_DISABLE: 1
